CREATE DATABASE Funct;
USE Funct;

CREATE TABLE CHECK_FUNCTI(
id INT PRIMARY KEY,
name VARCHAR(50),
MArks INT NOT NULL,
Grade VARCHAR(10),
City VARCHAR(50)
);

INSERT INTO CHECK_FUNCTI VALUES (1, "Gulshid Zada", 600, "A+", "Peshawar");
INSERT INTO CHECK_FUNCTI VALUES (2, "Muhammad", 500, "A", "Hangu");
INSERT INTO CHECK_FUNCTI VALUES (3, "Rafi Ullah", 400, "B", "Hangu");
INSERT INTO CHECK_FUNCTI VALUES (4, "Faraz Ahmad", 450, "B+", "Peshawar");
INSERT INTO CHECK_FUNCTI VALUES (5, "Ubaid Ullah", 560, "A", "Kohat");
INSERT INTO CHECK_FUNCTI VALUES (6, "Hassan Khan", 520, "A", "Islamabad");

SELECT * FROM CHECK_FUNCTI;
-- LETS APPLY AGGREGATE FUNCTION
SELECT count(id) FROM CHECK_FUNCTI;
SELECT count(MArks) FROM CHECK_FUNCTI;
SELECT sum(MArks) FROM CHECK_FUNCTI;
SELECT MAX(MARKS)  FROM CHECK_FUNCTI;
SELECT MIN(MARKS)  FROM CHECK_FUNCTI;
SELECT AVG(MARKS)  FROM CHECK_FUNCTI;


SELECT City, COUNT(id) FROM CHECK_FUNCTI GROUP BY City;
SELECT City, avg(MArks) FROM CHECK_FUNCTI GROUP BY City;
SELECT name FROM CHECK_FUNCT;


CREATE TABLE INfo(
Roll_no INT PRIMARY KEY,
Marks INT ,
City VARCHAR(50)
);

INSERT INTO INfo(Roll_no, Marks, City) VALUES 
(10, 300, "HANGU"),
(20, 280, "PESHAWAR"),
(30, 250, "PESHAWAR"),
(40, 270, "HANGU"),
(50, 230, "KARACHI"),
(60, 203, "KARACHI");

SELECT City, COUNT(Roll_no) FROM INfo GROUP BY City;


CREATE TABLE Student(
id INT PRIMARY KEY,
name VARCHAR(40),
Roll_no INT,
FOREIGN KEY (id)  REFERENCES COURSE(id)
ON DELETE CASCADE
ON UPDATE CASCADE
);

CREATE TABLE COURSE(
id INT PRIMARY KEY,
COURSE_ID INT ,
COURSE_NAME VARCHAR(50)
);

